version: '3'
services:
  postgres-rest-api:
    image: postgres:11-alpine
    container_name: rest-api-db
    environment:
      - "POSTGRES_PASSWORD=local"
      - "POSTGRES_USER=rest-api"
      - "POSTGRES_DB=rest-api"
    ports:
      - 5490:5432