server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST:localhost}:${PG_DB_PORT:5490}/rest-api?stringtype=unspecified
    username: "${POSTGRES_USERNAME:rest-api}"
    password: "${POSTGRES_PASSWORD:local}"
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

info:
  app:
    version: 0.0.1